# [empty](http://reactivex.io/documentation/operators/empty-never-throw.html)
아무 데이터도 발생시키지 않는 Observable을 만듭니다. onCompleted만 호출됩니다.
![empty.c.png](http://reactivex.io/documentation/operators/images/empty.c.png)

### 샘플 코드
```java
// RxJava1
public static void main(String[] args) {
    Observable
            .empty()
            .subscribe(
                    item -> System.out.println("Thread:" + Thread.currentThread().getName() + "\tonNext: " + item), // 호출되지 않습니다.
                    e -> System.out.println("Thread:" + Thread.currentThread().getName() + "\tonError: " + e.getMessage()), // 호출되지 않습니다.
                    () -> System.out.println("Thread:" + Thread.currentThread().getName() + "\tonCompleted")
            );

    try {
        Thread.sleep(2000);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
}
```
<br>
<br>

# [never](http://reactivex.io/documentation/operators/empty-never-throw.html)
기본적으로 empty와 같지만, onCompleted도 호출되지 않습니다.
![never.c.png](http://reactivex.io/documentation/operators/images/never.c.png)

### 샘플 코드
```java
// RxJava1
public static void main(String[] args) {
    Observable
            .never()
            .subscribe(
                    item -> System.out.println("Thread:" + Thread.currentThread().getName() + "\tonNext: " + item), // 호출되지 않습니다.
                    e -> System.out.println("Thread:" + Thread.currentThread().getName() + "\tonError: " + e.getMessage()), // 호출되지 않습니다.
                    () -> System.out.println("Thread:" + Thread.currentThread().getName() + "\tonCompleted") // 호출되지 않습니다.
            );

    try {
        Thread.sleep(2000);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
}
```
<br>
<br>

# [throw](http://reactivex.io/documentation/operators/empty-never-throw.html)
기본적으로 empty와 같지만, onCompleted 대신에 onError가 호출됩니다. ```Observable.error()```로 사용해야 함에 주의
![throw.c.png](http://reactivex.io/documentation/operators/images/throw.c.png)

### 샘플 코드
```java
// RxJava1
public static void main(String[] args) {
    Observable
            .error(new Exception("에러입니다."))
            .subscribe(
                    item -> System.out.println("Thread:" + Thread.currentThread().getName() + "\tonNext: " + item), // 호출되지 않습니다.
                    (e) -> {
                        // doOnError는 에러를 통보받을 뿐이지 catch할 수는 없습니다.
                        // subscribe()에 onError콜백을 넣어주어야 threadException이 발생하지 않습니다.
                        System.err.println("Thread:" + Thread.currentThread().getName() + "\tonError: " + e.getMessage());
                    },
                    () -> System.out.println("Thread:" + Thread.currentThread().getName() + "\tonCompleted") // 호출되지 않습니다.
            );

    try {
        Thread.sleep(2000);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
}
```
